<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class QaMasterSeeder extends Seeder
{
    private function inferSatuan(string $parameterName): ?string
    {
        $name = strtolower($parameterName);

        if (str_contains($name, 'ph')) return 'pH';
        if (str_contains($name, 'alkohol') || str_contains($name, 'tsai')) return '%';
        if (str_contains($name, 'brix') || str_contains($name, 'pol') || str_contains($name, 'hk') || str_contains($name, 'kadar air') || str_contains($name, 'sulf.')) return '%';
        if (str_contains($name, 'suhu')) return '°C';
        if (str_contains($name, 'permanganat')) return 'menit';
        if (str_contains($name, 'tekanan')) return 'bar';
        if (str_contains($name, 'kapur') || str_contains($name, 'tds')) return 'ppm';
        if (str_contains($name, 'diameter')) return 'mm';
        if (str_contains($name, 'kuintal') || str_contains($name, ' ku') || str_contains($name, 'ku.')) return 'ku';
        if (str_contains($name, 'ton')) return 'ton';
        if (str_contains($name, 'jam')) return 'jam';
        if (str_contains($name, 'hari')) return 'hari';
        if (str_contains($name, 'icumsa')) return 'IU';

        return null;
    }

    private function makeParameter(array $stasiunId, string $stasiunName, string $namaParameter, string $operator, ?float $batasBawah, ?float $batasAtas, $now, ?string $satuan = null): array
    {
        return [
            'stasiun_id' => $stasiunId[$stasiunName] ?? null,
            'nama_parameter' => $namaParameter,
            'satuan' => $satuan,
            'operator_kondisi' => $operator,
            'batas_bawah' => $batasBawah,
            'batas_atas' => $batasAtas,
            'is_aktif' => true,
            'created_at' => $now,
            'updated_at' => $now,
        ];
    }

    private function buildAlcoholParameters(array $stasiunId, $now): array
    {
        $rows = [];

        $bahanBaku = 'Alkohol - Bahan Baku';
        $masakan = 'Alkohol - Stasiun Masakan';
        $peragian = 'Alkohol - Stasiun Peragian';
        $sulingan = 'Alkohol - Stasiun Sulingan / Produksi';
        $gudang = 'Alkohol - Gudang Penimbunan Sementara';

        $rows[] = $this->makeParameter($stasiunId, $bahanBaku, 'Brix Tetes', '>', 85, null, $now);
        $rows[] = $this->makeParameter($stasiunId, $bahanBaku, 'TSAI Tetes', '>', 55, null, $now);

        $rows[] = $this->makeParameter($stasiunId, $masakan, 'Brix Adonan 3A', '>=', 14, null, $now);
        $rows[] = $this->makeParameter($stasiunId, $masakan, 'Brix Adonan 3B', '>=', 18, null, $now);
        $rows[] = $this->makeParameter($stasiunId, $masakan, 'Brix Adonan 8-1', '>=', 55, null, $now);
        $rows[] = $this->makeParameter($stasiunId, $masakan, 'Brix Adonan 8-2', '>=', 55, null, $now);
        $rows[] = $this->makeParameter($stasiunId, $masakan, 'Brix Adonan 8-3', '>=', 55, null, $now);
        $rows[] = $this->makeParameter($stasiunId, $masakan, 'pH Adonan 3A', 'BETWEEN', 4.5, 5.2, $now);
        $rows[] = $this->makeParameter($stasiunId, $masakan, 'pH Adonan 3B', 'BETWEEN', 4.5, 5.2, $now);
        $rows[] = $this->makeParameter($stasiunId, $masakan, 'pH Adonan 8-1', 'BETWEEN', 4.5, 5.2, $now);
        $rows[] = $this->makeParameter($stasiunId, $masakan, 'pH Adonan 8-2', 'BETWEEN', 4.5, 5.2, $now);
        $rows[] = $this->makeParameter($stasiunId, $masakan, 'pH Adonan 8-3', 'BETWEEN', 4.5, 5.2, $now);

        foreach (['22/1', '22/2', '22/3'] as $kode) {
            $rows[] = $this->makeParameter($stasiunId, $peragian, "Brix Beslag T {$kode}", 'BETWEEN', 4, 13, $now);
        }

        foreach (['25/1', '25/2', '25/3'] as $kode) {
            $rows[] = $this->makeParameter($stasiunId, $peragian, "Brix Beslag T {$kode}", 'BETWEEN', 5, 15, $now);
        }

        for ($i = 1; $i <= 10; $i++) {
            $rows[] = $this->makeParameter($stasiunId, $peragian, "Brix Beslag T 26/{$i}", 'BETWEEN', 7, 23, $now);
        }

        for ($i = 1; $i <= 10; $i++) {
            $rows[] = $this->makeParameter($stasiunId, $peragian, "Suhu Beslag T 26/{$i}", '<=', null, 34, $now);
        }

        for ($i = 1; $i <= 10; $i++) {
            $rows[] = $this->makeParameter($stasiunId, $peragian, "Kadar Alkohol Beslag T 26/{$i}", '>=', 8, null, $now);
        }

        $rows[] = $this->makeParameter($stasiunId, $sulingan, 'Kadar Alkohol Nachlop', '>=', 95, null, $now);
        $rows[] = $this->makeParameter($stasiunId, $sulingan, 'Kadar Alkohol Rektifiser', '>=', 95, null, $now);
        $rows[] = $this->makeParameter($stasiunId, $sulingan, 'Kadar Alkohol Voorlop', '>=', 94, null, $now);

        $rows[] = $this->makeParameter($stasiunId, $gudang, 'Kadar Alkohol Nachlop T-1', '>=', 95, null, $now);
        $rows[] = $this->makeParameter($stasiunId, $gudang, 'Kadar Alkohol Nachlop T-2', '>=', 95, null, $now);
        $rows[] = $this->makeParameter($stasiunId, $gudang, 'Kadar Alkohol Prima T-1', '>=', 95, null, $now);
        $rows[] = $this->makeParameter($stasiunId, $gudang, 'Kadar Alkohol Prima T-2', '>=', 95, null, $now);
        $rows[] = $this->makeParameter($stasiunId, $gudang, 'Kadar Alkohol Prima T-3', '>=', 95, null, $now);
        $rows[] = $this->makeParameter($stasiunId, $gudang, 'Kadar Alkohol Teknis T-1', '>=', 94, null, $now);
        $rows[] = $this->makeParameter($stasiunId, $gudang, 'Kadar Alkohol Teknis T-2', '>=', 94, null, $now);
        $rows[] = $this->makeParameter($stasiunId, $gudang, 'Kadar Alkohol Teknis T-3', '>=', 94, null, $now);
        $rows[] = $this->makeParameter($stasiunId, $gudang, 'Uji Permanganat Alkohol Nachlop T-1', '>=', 15, null, $now);
        $rows[] = $this->makeParameter($stasiunId, $gudang, 'Uji Permanganat Alkohol Nachlop T-2', '>=', 15, null, $now);
        $rows[] = $this->makeParameter($stasiunId, $gudang, 'Uji Permanganat Alkohol Prima T-1', '>=', 15, null, $now);
        $rows[] = $this->makeParameter($stasiunId, $gudang, 'Uji Permanganat Alkohol Prima T-2', '>=', 15, null, $now);
        $rows[] = $this->makeParameter($stasiunId, $gudang, 'Uji Permanganat Alkohol Prima T-3', '>=', 15, null, $now);

        return $rows;
    }

    public function run(): void
    {
        DB::connection('pgsql')->transaction(function () {
            $now = now();

            $stasiun = [
                ['nama_stasiun' => 'Stasiun Gilingan', 'created_at' => $now, 'updated_at' => $now],
                ['nama_stasiun' => 'Stasiun Pemurnian', 'created_at' => $now, 'updated_at' => $now],
                ['nama_stasiun' => 'Stasiun Penguapan', 'created_at' => $now, 'updated_at' => $now],
                ['nama_stasiun' => 'Stasiun Masakan', 'created_at' => $now, 'updated_at' => $now],
                ['nama_stasiun' => 'Stasiun Puteran', 'created_at' => $now, 'updated_at' => $now],
                ['nama_stasiun' => 'Stasiun Ketel', 'created_at' => $now, 'updated_at' => $now],
                ['nama_stasiun' => 'Stasiun Produksi', 'created_at' => $now, 'updated_at' => $now],
                ['nama_stasiun' => 'Neraca Warna', 'created_at' => $now, 'updated_at' => $now],
                ['nama_stasiun' => 'Alkohol - Bahan Baku', 'created_at' => $now, 'updated_at' => $now],
                ['nama_stasiun' => 'Alkohol - Stasiun Masakan', 'created_at' => $now, 'updated_at' => $now],
                ['nama_stasiun' => 'Alkohol - Stasiun Peragian', 'created_at' => $now, 'updated_at' => $now],
                ['nama_stasiun' => 'Alkohol - Stasiun Sulingan / Produksi', 'created_at' => $now, 'updated_at' => $now],
                ['nama_stasiun' => 'Alkohol - Gudang Penimbunan Sementara', 'created_at' => $now, 'updated_at' => $now],
            ];

            DB::connection('pgsql')->table('mst_stasiun')->upsert(
                $stasiun,
                ['nama_stasiun'],
                ['updated_at']
            );

            $stasiunId = DB::connection('pgsql')->table('mst_stasiun')->pluck('id', 'nama_stasiun');

            $parameter = [
                // STASIUN GILINGAN =======================================
                [
                    'stasiun_id' => $stasiunId['Stasiun Gilingan'] ?? null,
                    'nama_parameter' => 'Kap. Gilingan',
                    'satuan' => 'ku',
                    'operator_kondisi' => '>',
                    'batas_bawah' => 1300,
                    'batas_atas' => null,
                    'is_aktif' => true,
                    'created_at' => $now,
                    'updated_at' => $now,
                ],
                [
                    'stasiun_id' => $stasiunId['Stasiun Gilingan'] ?? null,
                    'nama_parameter' => 'Gil. 1 Brix',
                    'operator_kondisi' => '>',
                    'batas_bawah' => 15,
                    'batas_atas' => null,
                    'is_aktif' => true,
                    'created_at' => $now,
                    'updated_at' => $now,
                ],
                [
                    'stasiun_id' => $stasiunId['Stasiun Gilingan'] ?? null,
                    'nama_parameter' => 'Gil. 1 Pol',
                    'operator_kondisi' => '>',
                    'batas_bawah' => 12,
                    'batas_atas' => null,
                    'is_aktif' => true,
                    'created_at' => $now,
                    'updated_at' => $now,
                ],
                [
                    'stasiun_id' => $stasiunId['Stasiun Gilingan'] ?? null,
                    'nama_parameter' => 'Gil. 1 HK',
                    'operator_kondisi' => 'NONE',
                    'batas_bawah' => null,
                    'batas_atas' => null,
                    'is_aktif' => true,
                    'created_at' => $now,
                    'updated_at' => $now,
                ],
                
                [
                    'stasiun_id' => $stasiunId['Stasiun Gilingan'] ?? null,
                    'nama_parameter' => 'Nilai NPP',
                    'operator_kondisi' => '>',
                    'batas_bawah' => 10.5,
                    'batas_atas' => null,
                    'is_aktif' => true,
                    'created_at' => $now,
                    'updated_at' => $now,
                ],
                [
                    'stasiun_id' => $stasiunId['Stasiun Gilingan'] ?? null,
                    'nama_parameter' => 'Gil. 2 Brix',
                    'operator_kondisi' => '<',
                    'batas_bawah' => null,
                    'batas_atas' => 8.5,
                    'is_aktif' => true,
                    'created_at' => $now,
                    'updated_at' => $now,
                ],
                [
                    'stasiun_id' => $stasiunId['Stasiun Gilingan'] ?? null,
                    'nama_parameter' => 'Gil. 2 Pol',
                    'operator_kondisi' => 'NONE',
                    'batas_bawah' => null,
                    'batas_atas' => null,
                    'is_aktif' => true,
                    'created_at' => $now,
                    'updated_at' => $now,
                ],
                [
                    'stasiun_id' => $stasiunId['Stasiun Gilingan'] ?? null,
                    'nama_parameter' => 'Gil. 2 HK',
                    'operator_kondisi' => 'NONE',
                    'batas_bawah' => null,
                    'batas_atas' => null,
                    'is_aktif' => true,
                    'created_at' => $now,
                    'updated_at' => $now,
                ],
                [
                    'stasiun_id' => $stasiunId['Stasiun Gilingan'] ?? null,
                    'nama_parameter' => 'Gil. 3 Brix',
                    'operator_kondisi' => '<',
                    'batas_bawah' => null,
                    'batas_atas' => 5.5,
                    'is_aktif' => true,
                    'created_at' => $now,
                    'updated_at' => $now,
                ],
                [
                    'stasiun_id' => $stasiunId['Stasiun Gilingan'] ?? null,
                    'nama_parameter' => 'Gil. 3 Pol',
                    'operator_kondisi' => 'NONE',
                    'batas_bawah' => null,
                    'batas_atas' => null,
                    'is_aktif' => true,
                    'created_at' => $now,
                    'updated_at' => $now,
                ],
                [
                    'stasiun_id' => $stasiunId['Stasiun Gilingan'] ?? null,
                    'nama_parameter' => 'Gil. 3 HK',
                    'operator_kondisi' => 'NONE',
                    'batas_bawah' => null,
                    'batas_atas' => null,
                    'is_aktif' => true,
                    'created_at' => $now,
                    'updated_at' => $now,
                ],
                [
                    'stasiun_id' => $stasiunId['Stasiun Gilingan'] ?? null,
                    'nama_parameter' => 'Gil. 4 Brix',
                    'operator_kondisi' => '<',
                    'batas_bawah' => null,
                    'batas_atas' => 4,
                    'is_aktif' => true,
                    'created_at' => $now,
                    'updated_at' => $now,
                ],
                [
                    'stasiun_id' => $stasiunId['Stasiun Gilingan'] ?? null,
                    'nama_parameter' => 'Gil. 4 Pol',
                    'operator_kondisi' => 'NONE',
                    'batas_bawah' => null,
                    'batas_atas' => null,
                    'is_aktif' => true,
                    'created_at' => $now,
                    'updated_at' => $now,
                ],
                [
                    'stasiun_id' => $stasiunId['Stasiun Gilingan'] ?? null,
                    'nama_parameter' => 'Gil. 4 HK',
                    'operator_kondisi' => 'NONE',
                    'batas_bawah' => null,
                    'batas_atas' => null,
                    'is_aktif' => true,
                    'created_at' => $now,
                    'updated_at' => $now,
                ],
                [
                    'stasiun_id' => $stasiunId['Stasiun Gilingan'] ?? null,
                    'nama_parameter' => 'Gil. 5 Brix',
                    'operator_kondisi' => '<',
                    'batas_bawah' => null,
                    'batas_atas' => 2,
                    'is_aktif' => true,
                    'created_at' => $now,
                    'updated_at' => $now,
                ],
                [
                    'stasiun_id' => $stasiunId['Stasiun Gilingan'] ?? null,
                    'nama_parameter' => 'Gil. 5 Pol',
                    'operator_kondisi' => 'NONE',
                    'batas_bawah' => null,
                    'batas_atas' => null,
                    'is_aktif' => true,
                    'created_at' => $now,
                    'updated_at' => $now,
                ],
                [
                    'stasiun_id' => $stasiunId['Stasiun Gilingan'] ?? null,
                    'nama_parameter' => 'Gil. 5 HK',
                    'operator_kondisi' => 'NONE',
                    'batas_bawah' => null,
                    'batas_atas' => null,
                    'is_aktif' => true,
                    'created_at' => $now,
                    'updated_at' => $now,
                ],
                [
                    'stasiun_id' => $stasiunId['Stasiun Gilingan'] ?? null,
                    'nama_parameter' => 'ZK Ampas',
                    'operator_kondisi' => '>',
                    'batas_bawah' => 50,
                    'batas_atas' => null,
                    'is_aktif' => true,
                    'created_at' => $now,
                    'updated_at' => $now,
                ],
                [
                    'stasiun_id' => $stasiunId['Stasiun Gilingan'] ?? null,
                    'nama_parameter' => 'Pol Ampas %',
                    'operator_kondisi' => '>',
                    'batas_bawah' => 50,
                    'batas_atas' => null,
                    'is_aktif' => true,
                    'created_at' => $now,
                    'updated_at' => $now,
                ],
                [
                    'stasiun_id' => $stasiunId['Stasiun Gilingan'] ?? null,
                    'nama_parameter' => 'Imbibisi Ku',
                    'operator_kondisi' => 'NONE',
                    'batas_bawah' => null,
                    'batas_atas' => null,
                    'is_aktif' => true,
                    'created_at' => $now,
                    'updated_at' => $now,
                ],
                [
                    'stasiun_id' => $stasiunId['Stasiun Gilingan'] ?? null,
                    'nama_parameter' => 'Imbibisi % Tebu',
                    'operator_kondisi' => 'NONE',
                    'batas_bawah' => null,
                    'batas_atas' => null,
                    'is_aktif' => true,
                    'created_at' => $now,
                    'updated_at' => $now,
                ],
                [
                    'stasiun_id' => $stasiunId['Stasiun Gilingan'] ?? null,
                    'nama_parameter' => 'NM pH',
                    'operator_kondisi' => 'BETWEEN',
                    'batas_bawah' => 5.0,
                    'batas_atas' => 5.5,
                    'is_aktif' => true,
                    'created_at' => $now,
                    'updated_at' => $now,
                ],
                [
                    'stasiun_id' => $stasiunId['Stasiun Gilingan'] ?? null,
                    'nama_parameter' => 'NM Brix',
                    'operator_kondisi' => '>',
                    'batas_bawah' => 11.5,
                    'batas_atas' => null,
                    'is_aktif' => true,
                    'created_at' => $now,
                    'updated_at' => $now,
                ],
                [
                    'stasiun_id' => $stasiunId['Stasiun Gilingan'] ?? null,
                    'nama_parameter' => 'NM Pol',
                    'operator_kondisi' => 'NONE',
                    'batas_bawah' => null,
                    'batas_atas' => null,
                    'is_aktif' => true,
                    'created_at' => $now,
                    'updated_at' => $now,
                ],
                [
                    'stasiun_id' => $stasiunId['Stasiun Gilingan'] ?? null,
                    'nama_parameter' => 'NM HK',
                    'operator_kondisi' => '>',
                    'batas_bawah' => 74,
                    'batas_atas' => null,
                    'is_aktif' => true,
                    'created_at' => $now,
                    'updated_at' => $now,
                ],
                [
                    'stasiun_id' => $stasiunId['Stasiun Gilingan'] ?? null,
                    'nama_parameter' => 'NM ku (Timbangan)',
                    'operator_kondisi' => 'NONE',
                    'batas_bawah' => null,
                    'batas_atas' => null,
                    'is_aktif' => true,
                    'created_at' => $now,
                    'updated_at' => $now,
                ],
                [
                    'stasiun_id' => $stasiunId['Stasiun Gilingan'] ?? null,
                    'nama_parameter' => 'NM Koreksi Kotor',
                    'operator_kondisi' => 'NONE',
                    'batas_bawah' => null,
                    'batas_atas' => null,
                    'is_aktif' => true,
                    'created_at' => $now,
                    'updated_at' => $now,
                ],
                [
                    'stasiun_id' => $stasiunId['Stasiun Gilingan'] ?? null,
                    'nama_parameter' => 'NM ku Netto',
                    'operator_kondisi' => 'NONE',
                    'batas_bawah' => null,
                    'batas_atas' => null,
                    'is_aktif' => true,
                    'created_at' => $now,
                    'updated_at' => $now,
                ],
                [
                    'stasiun_id' => $stasiunId['Stasiun Gilingan'] ?? null,
                    'nama_parameter' => 'NM % Tebu',
                    'operator_kondisi' => '>',
                    'batas_bawah' => 100,
                    'batas_atas' => null,
                    'is_aktif' => true,
                    'created_at' => $now,
                    'updated_at' => $now,
                ],
                [
                    'stasiun_id' => $stasiunId['Stasiun Gilingan'] ?? null,
                    'nama_parameter' => 'NM GuRed',
                    'operator_kondisi' => 'NONE',
                    'batas_bawah' => null,
                    'batas_atas' => null,
                    'is_aktif' => true,
                    'created_at' => $now,
                    'updated_at' => $now,
                ],
                [
                    'stasiun_id' => $stasiunId['Stasiun Gilingan'] ?? null,
                    'nama_parameter' => 'pH NPP',
                    'operator_kondisi' => '>',
                    'batas_bawah' => 5,
                    'batas_atas' => null,
                    'is_aktif' => true,
                    'created_at' => $now,
                    'updated_at' => $now,
                ],
                [
                    'stasiun_id' => $stasiunId['Stasiun Gilingan'] ?? null,
                    'nama_parameter' => 'GuRed NPP',
                    'operator_kondisi' => 'NONE',
                    'batas_bawah' => null,
                    'batas_atas' => null,
                    'is_aktif' => true,
                    'created_at' => $now,
                    'updated_at' => $now,
                ],
                [
                    'stasiun_id' => $stasiunId['Stasiun Gilingan'] ?? null,
                    'nama_parameter' => 'NM P205 (Pospat)',
                    'operator_kondisi' => '>',
                    'batas_bawah' => 325,
                    'batas_atas' => null,
                    'is_aktif' => true,
                    'created_at' => $now,
                    'updated_at' => $now,
                ],
                [
                    'stasiun_id' => $stasiunId['Stasiun Gilingan'] ?? null,
                    'nama_parameter' => 'PSHK',
                    'operator_kondisi' => '>',
                    'batas_bawah' => 96,
                    'batas_atas' => null,
                    'is_aktif' => true,
                    'created_at' => $now,
                    'updated_at' => $now,
                ],

                // STASIUN PEMURNIAN =======================================
                [
                    'stasiun_id' => $stasiunId['Stasiun Pemurnian'] ?? null,
                    'nama_parameter' => 'NE Brix',
                    'operator_kondisi' => '<',
                    'batas_bawah' => null,
                    'batas_atas' => 12,
                    'is_aktif' => true,
                    'created_at' => $now,
                    'updated_at' => $now,
                ],
                [
                    'stasiun_id' => $stasiunId['Stasiun Pemurnian'] ?? null,
                    'nama_parameter' => 'NE Pol',
                    'operator_kondisi' => 'NONE',
                    'batas_bawah' => null,
                    'batas_atas' => null,
                    'is_aktif' => true,
                    'created_at' => $now,
                    'updated_at' => $now,
                ],
                [
                    'stasiun_id' => $stasiunId['Stasiun Pemurnian'] ?? null,
                    'nama_parameter' => 'NE HK',
                    'operator_kondisi' => '>',
                    'batas_bawah' => 76,
                    'batas_atas' => null,
                    'is_aktif' => true,
                    'created_at' => $now,
                    'updated_at' => $now,
                ],
                [
                    'stasiun_id' => $stasiunId['Stasiun Pemurnian'] ?? null,
                    'nama_parameter' => 'NE Turbidity',
                    'operator_kondisi' => '<',
                    'batas_bawah' => null,
                    'batas_atas' => 100,
                    'is_aktif' => true,
                    'created_at' => $now,
                    'updated_at' => $now,
                ],
                [
                    'stasiun_id' => $stasiunId['Stasiun Pemurnian'] ?? null,
                    'nama_parameter' => 'NE CaO (Kapur)',
                    'operator_kondisi' => '<',
                    'batas_bawah' => null,
                    'batas_atas' => 100,
                    'is_aktif' => true,
                    'created_at' => $now,
                    'updated_at' => $now,
                ],
                [
                    'stasiun_id' => $stasiunId['Stasiun Pemurnian'] ?? null,
                    'nama_parameter' => 'NE pH',
                    'operator_kondisi' => 'BETWEEN',
                    'batas_bawah' => 7.0,
                    'batas_atas' => 7.2,
                    'is_aktif' => true,
                    'created_at' => $now,
                    'updated_at' => $now,
                ],
                [
                    'stasiun_id' => $stasiunId['Stasiun Pemurnian'] ?? null,
                    'nama_parameter' => 'NE GuRed',
                    'operator_kondisi' => 'NONE',
                    'batas_bawah' => null,
                    'batas_atas' => null,
                    'is_aktif' => true,
                    'created_at' => $now,
                    'updated_at' => $now,
                ],
                [
                    'stasiun_id' => $stasiunId['Stasiun Pemurnian'] ?? null,
                    'nama_parameter' => 'Blothong Pol',
                    'operator_kondisi' => '<',
                    'batas_bawah' => null,
                    'batas_atas' => 2.5,
                    'is_aktif' => true,
                    'created_at' => $now,
                    'updated_at' => $now,
                ],
                [
                    'stasiun_id' => $stasiunId['Stasiun Pemurnian'] ?? null,
                    'nama_parameter' => 'Blothong ZK',
                    'operator_kondisi' => '>',
                    'batas_bawah' => 30,
                    'batas_atas' => null,
                    'is_aktif' => true,
                    'created_at' => $now,
                    'updated_at' => $now,
                ],

                // STASIUN PENGUAPAN ======================================
                [
                    'stasiun_id' => $stasiunId['Stasiun Penguapan'] ?? null,
                    'nama_parameter' => 'Tek. UB Penguapan',
                    'operator_kondisi' => 'BETWEEN',
                    'batas_bawah' => 0.6,
                    'batas_atas' => 0.9,
                    'is_aktif' => true,
                    'created_at' => $now,
                    'updated_at' => $now,
                ],
                [
                    'stasiun_id' => $stasiunId['Stasiun Penguapan'] ?? null,
                    'nama_parameter' => 'Temp UB Penguapan',
                    'operator_kondisi' => 'BETWEEN',
                    'batas_bawah' => 115,
                    'batas_atas' => 125,
                    'is_aktif' => true,
                    'created_at' => $now,
                    'updated_at' => $now,
                ],
                [
                    'stasiun_id' => $stasiunId['Stasiun Penguapan'] ?? null,
                    'nama_parameter' => 'Tek Vacum',
                    'operator_kondisi' => '>',
                    'batas_bawah' => 60,
                    'batas_atas' => null,
                    'is_aktif' => true,
                    'created_at' => $now,
                    'updated_at' => $now,
                ],
                [
                    'stasiun_id' => $stasiunId['Stasiun Penguapan'] ?? null,
                    'nama_parameter' => 'NK Brix',
                    'operator_kondisi' => '>',
                    'batas_bawah' => 60,
                    'batas_atas' => null,
                    'is_aktif' => true,
                    'created_at' => $now,
                    'updated_at' => $now,
                ],
                [
                    'stasiun_id' => $stasiunId['Stasiun Penguapan'] ?? null,
                    'nama_parameter' => 'NK Pol',
                    'operator_kondisi' => 'NONE',
                    'batas_bawah' => null,
                    'batas_atas' => null,
                    'is_aktif' => true,
                    'created_at' => $now,
                    'updated_at' => $now,
                ],
                [
                    'stasiun_id' => $stasiunId['Stasiun Penguapan'] ?? null,
                    'nama_parameter' => 'NK HK',
                    'operator_kondisi' => '>',
                    'batas_bawah' => 76,
                    'batas_atas' => null,
                    'is_aktif' => true,
                    'created_at' => $now,
                    'updated_at' => $now,
                ],
                [
                    'stasiun_id' => $stasiunId['Stasiun Penguapan'] ?? null,
                    'nama_parameter' => 'NK pH',
                    'operator_kondisi' => 'BETWEEN',
                    'batas_bawah' => 6.5,
                    'batas_atas' => 6.7,
                    'is_aktif' => true,
                    'created_at' => $now,
                    'updated_at' => $now,
                ],
                [
                    'stasiun_id' => $stasiunId['Stasiun Penguapan'] ?? null,
                    'nama_parameter' => 'NK Sulf Brix',
                    'operator_kondisi' => '>',
                    'batas_bawah' => 60,
                    'batas_atas' => null,
                    'is_aktif' => true,
                    'created_at' => $now,
                    'updated_at' => $now,
                ],
                [
                    'stasiun_id' => $stasiunId['Stasiun Penguapan'] ?? null,
                    'nama_parameter' => 'NK Sulf Pol',
                    'operator_kondisi' => 'NONE',
                    'batas_bawah' => null,
                    'batas_atas' => null,
                    'is_aktif' => true,
                    'created_at' => $now,
                    'updated_at' => $now,
                ],
                [
                    'stasiun_id' => $stasiunId['Stasiun Penguapan'] ?? null,
                    'nama_parameter' => 'NK Sulf HK',
                    'operator_kondisi' => '>',
                    'batas_bawah' => 76,
                    'batas_atas' => null,
                    'is_aktif' => true,
                    'created_at' => $now,
                    'updated_at' => $now,
                ],
                [
                    'stasiun_id' => $stasiunId['Stasiun Penguapan'] ?? null,
                    'nama_parameter' => 'NK Sulf pH',
                    'operator_kondisi' => 'BETWEEN',
                    'batas_bawah' => 5.0,
                    'batas_atas' => 5.5,
                    'is_aktif' => true,
                    'created_at' => $now,
                    'updated_at' => $now,
                ],
                [
                    'stasiun_id' => $stasiunId['Stasiun Penguapan'] ?? null,
                    'nama_parameter' => 'NK GuRed',
                    'operator_kondisi' => 'NONE',
                    'batas_bawah' => null,
                    'batas_atas' => null,
                    'is_aktif' => true,
                    'created_at' => $now,
                    'updated_at' => $now,
                ],
                [
                    'stasiun_id' => $stasiunId['Stasiun Penguapan'] ?? null,
                    'nama_parameter' => 'NK Sulf GuRed',
                    'operator_kondisi' => 'NONE',
                    'batas_bawah' => null,
                    'batas_atas' => null,
                    'is_aktif' => true,
                    'created_at' => $now,
                    'updated_at' => $now,
                ],
                
                // STASIUN MASAKAN =======================================
                [
                    'stasiun_id' => $stasiunId['Stasiun Masakan'] ?? null,
                    'nama_parameter' => 'Tek. UB Masakan',
                    'operator_kondisi' => 'BETWEEN',
                    'batas_bawah' => 0.6,
                    'batas_atas' => 0.9,
                    'is_aktif' => true,
                    'created_at' => $now,
                    'updated_at' => $now,
                ],
                [
                    'stasiun_id' => $stasiunId['Stasiun Masakan'] ?? null,
                    'nama_parameter' => 'Temp UB Masakan',
                    'operator_kondisi' => 'BETWEEN',
                    'batas_bawah' => 115,
                    'batas_atas' => 125,
                    'is_aktif' => true,
                    'created_at' => $now,
                    'updated_at' => $now,
                ],
                [
                    'stasiun_id' => $stasiunId['Stasiun Masakan'] ?? null,
                    'nama_parameter' => 'Vacum Pan Masakan',
                    'operator_kondisi' => '>',
                    'batas_bawah' => 60,
                    'batas_atas' => null,
                    'is_aktif' => true,
                    'created_at' => $now,
                    'updated_at' => $now,
                ],
                [
                    'stasiun_id' => $stasiunId['Stasiun Masakan'] ?? null,
                    'nama_parameter' => 'Masakan A Brix',
                    'operator_kondisi' => 'BETWEEN',
                    'batas_bawah' => 92,
                    'batas_atas' => 94,
                    'is_aktif' => true,
                    'created_at' => $now,
                    'updated_at' => $now,
                ],
                [
                    'stasiun_id' => $stasiunId['Stasiun Masakan'] ?? null,
                    'nama_parameter' => 'Masakan A Pol',
                    'operator_kondisi' => 'NONE',
                    'batas_bawah' => null,
                    'batas_atas' => null,
                    'is_aktif' => true,
                    'created_at' => $now,
                    'updated_at' => $now,
                ],
                [
                    'stasiun_id' => $stasiunId['Stasiun Masakan'] ?? null,
                    'nama_parameter' => 'Masakan A HK',
                    'operator_kondisi' => '>',
                    'batas_bawah' => 80,
                    'batas_atas' => null,
                    'is_aktif' => true,
                    'created_at' => $now,
                    'updated_at' => $now,
                ],
                [
                    'stasiun_id' => $stasiunId['Stasiun Masakan'] ?? null,
                    'nama_parameter' => 'Masakan C Brix',
                    'operator_kondisi' => 'BETWEEN',
                    'batas_bawah' => 94,
                    'batas_atas' => 96,
                    'is_aktif' => true,
                    'created_at' => $now,
                    'updated_at' => $now,
                ],
                [
                    'stasiun_id' => $stasiunId['Stasiun Masakan'] ?? null,
                    'nama_parameter' => 'Masakan C Pol',
                    'operator_kondisi' => 'NONE',
                    'batas_bawah' => null,
                    'batas_atas' => null,
                    'is_aktif' => true,
                    'created_at' => $now,
                    'updated_at' => $now,
                ],
                [
                    'stasiun_id' => $stasiunId['Stasiun Masakan'] ?? null,
                    'nama_parameter' => 'Masakan C HK',
                    'operator_kondisi' => 'BETWEEN',
                    'batas_bawah' => 70,
                    'batas_atas' => 73,
                    'is_aktif' => true,
                    'created_at' => $now,
                    'updated_at' => $now,
                ],
                [
                    'stasiun_id' => $stasiunId['Stasiun Masakan'] ?? null,
                    'nama_parameter' => 'Masakan D Brix',
                    'operator_kondisi' => 'BETWEEN',
                    'batas_bawah' => 97,
                    'batas_atas' => 99,
                    'is_aktif' => true,
                    'created_at' => $now,
                    'updated_at' => $now,
                ],
                [
                    'stasiun_id' => $stasiunId['Stasiun Masakan'] ?? null,
                    'nama_parameter' => 'Masakan D Pol',
                    'operator_kondisi' => 'NONE',
                    'batas_bawah' => null,
                    'batas_atas' => null,
                    'is_aktif' => true,
                    'created_at' => $now,
                    'updated_at' => $now,
                ],
                [
                    'stasiun_id' => $stasiunId['Stasiun Masakan'] ?? null,
                    'nama_parameter' => 'Masakan D HK',
                    'operator_kondisi' => 'BETWEEN',
                    'batas_bawah' => 58,
                    'batas_atas' => 61,
                    'is_aktif' => true,
                    'created_at' => $now,
                    'updated_at' => $now,
                ],

                // STASIUN PUTERAN =======================================
                [
                    'stasiun_id' => $stasiunId['Stasiun Puteran'] ?? null,
                    'nama_parameter' => 'Klare A Brix',
                    'operator_kondisi' => 'BETWEEN',
                    'batas_bawah' => 72,
                    'batas_atas' => 77,
                    'is_aktif' => true,
                    'created_at' => $now,
                    'updated_at' => $now,
                ],
                [
                    'stasiun_id' => $stasiunId['Stasiun Puteran'] ?? null,
                    'nama_parameter' => 'Klare A Pol',
                    'operator_kondisi' => 'NONE',
                    'batas_bawah' => null,
                    'batas_atas' => null,
                    'is_aktif' => true,
                    'created_at' => $now,
                    'updated_at' => $now,
                ],
                [
                    'stasiun_id' => $stasiunId['Stasiun Puteran'] ?? null,
                    'nama_parameter' => 'Klare A HK',
                    'operator_kondisi' => 'NONE',
                    'batas_bawah' => null,
                    'batas_atas' => null,
                    'is_aktif' => true,
                    'created_at' => $now,
                    'updated_at' => $now,
                ],
                [
                    'stasiun_id' => $stasiunId['Stasiun Puteran'] ?? null,
                    'nama_parameter' => 'Klare D Brix',
                    'operator_kondisi' => 'BETWEEN',
                    'batas_bawah' => 80,
                    'batas_atas' => 83,
                    'is_aktif' => true,
                    'created_at' => $now,
                    'updated_at' => $now,
                ],
                [
                    'stasiun_id' => $stasiunId['Stasiun Puteran'] ?? null,
                    'nama_parameter' => 'Klare D Pol',
                    'operator_kondisi' => 'NONE',
                    'batas_bawah' => null,
                    'batas_atas' => null,
                    'is_aktif' => true,
                    'created_at' => $now,
                    'updated_at' => $now,
                ],
                [
                    'stasiun_id' => $stasiunId['Stasiun Puteran'] ?? null,
                    'nama_parameter' => 'Klare D HK',
                    'operator_kondisi' => 'NONE',
                    'batas_bawah' => null,
                    'batas_atas' => null,
                    'is_aktif' => true,
                    'created_at' => $now,
                    'updated_at' => $now,
                ],
                [
                    'stasiun_id' => $stasiunId['Stasiun Puteran'] ?? null,
                    'nama_parameter' => 'Stroop A Brix',
                    'operator_kondisi' => 'BETWEEN',
                    'batas_bawah' => 80,
                    'batas_atas' => 83,
                    'is_aktif' => true,
                    'created_at' => $now,
                    'updated_at' => $now,
                ],
                [
                    'stasiun_id' => $stasiunId['Stasiun Puteran'] ?? null,
                    'nama_parameter' => 'Stroop A Pol',
                    'operator_kondisi' => 'NONE',
                    'batas_bawah' => null,
                    'batas_atas' => null,
                    'is_aktif' => true,
                    'created_at' => $now,
                    'updated_at' => $now,
                ],
                [
                    'stasiun_id' => $stasiunId['Stasiun Puteran'] ?? null,
                    'nama_parameter' => 'Stroop A HK',
                    'operator_kondisi' => '<',
                    'batas_bawah' => null,
                    'batas_atas' => 64,
                    'is_aktif' => true,
                    'created_at' => $now,
                    'updated_at' => $now,
                ],
                [
                    'stasiun_id' => $stasiunId['Stasiun Puteran'] ?? null,
                    'nama_parameter' => 'Stroop C Brix',
                    'operator_kondisi' => 'BETWEEN',
                    'batas_bawah' => 80,
                    'batas_atas' => 83,
                    'is_aktif' => true,
                    'created_at' => $now,
                    'updated_at' => $now,
                ],
                [
                    'stasiun_id' => $stasiunId['Stasiun Puteran'] ?? null,
                    'nama_parameter' => 'Stroop C Pol',
                    'operator_kondisi' => 'NONE',
                    'batas_bawah' => null,
                    'batas_atas' => null,
                    'is_aktif' => true,
                    'created_at' => $now,
                    'updated_at' => $now,
                ],
                [
                    'stasiun_id' => $stasiunId['Stasiun Puteran'] ?? null,
                    'nama_parameter' => 'Stroop C HK',
                    'operator_kondisi' => 'NONE',
                    'batas_bawah' => null,
                    'batas_atas' => null,
                    'is_aktif' => true,
                    'created_at' => $now,
                    'updated_at' => $now,
                ],
                [
                    'stasiun_id' => $stasiunId['Stasiun Puteran'] ?? null,
                    'nama_parameter' => 'Tetes ku (Timbangan)',
                    'operator_kondisi' => 'NONE',
                    'batas_bawah' => null,
                    'batas_atas' => null,
                    'is_aktif' => true,
                    'created_at' => $now,
                    'updated_at' => $now,
                ],
                [
                    'stasiun_id' => $stasiunId['Stasiun Puteran'] ?? null,
                    'nama_parameter' => 'Tetes Brix',
                    'operator_kondisi' => 'BETWEEN',
                    'batas_bawah' => 83,
                    'batas_atas' => 86,
                    'is_aktif' => true,
                    'created_at' => $now,
                    'updated_at' => $now,
                ],
                [
                    'stasiun_id' => $stasiunId['Stasiun Puteran'] ?? null,
                    'nama_parameter' => 'Tetes Pol',
                    'operator_kondisi' => 'NONE',
                    'batas_bawah' => null,
                    'batas_atas' => null,
                    'is_aktif' => true,
                    'created_at' => $now,
                    'updated_at' => $now,
                ],
                [
                    'stasiun_id' => $stasiunId['Stasiun Puteran'] ?? null,
                    'nama_parameter' => 'Tetes HK',
                    'operator_kondisi' => '<',
                    'batas_bawah' => null,
                    'batas_atas' => 33,
                    'is_aktif' => true,
                    'created_at' => $now,
                    'updated_at' => $now,
                ],
                [
                    'stasiun_id' => $stasiunId['Stasiun Puteran'] ?? null,
                    'nama_parameter' => 'Gula C Brix',
                    'operator_kondisi' => 'NONE',
                    'batas_bawah' => null,
                    'batas_atas' => null,
                    'is_aktif' => true,
                    'created_at' => $now,
                    'updated_at' => $now,
                ],
                [
                    'stasiun_id' => $stasiunId['Stasiun Puteran'] ?? null,
                    'nama_parameter' => 'Gula C Pol',
                    'operator_kondisi' => 'NONE',
                    'batas_bawah' => null,
                    'batas_atas' => null,
                    'is_aktif' => true,
                    'created_at' => $now,
                    'updated_at' => $now,
                ],
                [
                    'stasiun_id' => $stasiunId['Stasiun Puteran'] ?? null,
                    'nama_parameter' => 'Gula C HK',
                    'operator_kondisi' => '<',
                    'batas_bawah' => null,
                    'batas_atas' => 33,
                    'is_aktif' => true,
                    'created_at' => $now,
                    'updated_at' => $now,
                ],
                [
                    'stasiun_id' => $stasiunId['Stasiun Puteran'] ?? null,
                    'nama_parameter' => 'Gula D1 Brix',
                    'operator_kondisi' => 'NONE',
                    'batas_bawah' => null,
                    'batas_atas' => null,
                    'is_aktif' => true,
                    'created_at' => $now,
                    'updated_at' => $now,
                ],
                [
                    'stasiun_id' => $stasiunId['Stasiun Puteran'] ?? null,
                    'nama_parameter' => 'Gula D1 Pol',
                    'operator_kondisi' => 'NONE',
                    'batas_bawah' => null,
                    'batas_atas' => null,
                    'is_aktif' => true,
                    'created_at' => $now,
                    'updated_at' => $now,
                ],
                [
                    'stasiun_id' => $stasiunId['Stasiun Puteran'] ?? null,
                    'nama_parameter' => 'Gula D1 HK',
                    'operator_kondisi' => '<',
                    'batas_bawah' => null,
                    'batas_atas' => 33,
                    'is_aktif' => true,
                    'created_at' => $now,
                    'updated_at' => $now,
                ],
                [
                    'stasiun_id' => $stasiunId['Stasiun Puteran'] ?? null,
                    'nama_parameter' => 'Gula D2 Brix',
                    'operator_kondisi' => 'NONE',
                    'batas_bawah' => null,
                    'batas_atas' => null,
                    'is_aktif' => true,
                    'created_at' => $now,
                    'updated_at' => $now,
                ],
                [
                    'stasiun_id' => $stasiunId['Stasiun Puteran'] ?? null,
                    'nama_parameter' => 'Gula D2 Pol',
                    'operator_kondisi' => 'NONE',
                    'batas_bawah' => null,
                    'batas_atas' => null,
                    'is_aktif' => true,
                    'created_at' => $now,
                    'updated_at' => $now,
                ],
                [
                    'stasiun_id' => $stasiunId['Stasiun Puteran'] ?? null,
                    'nama_parameter' => 'Gula D2 HK',
                    'operator_kondisi' => '<',
                    'batas_bawah' => null,
                    'batas_atas' => 33,
                    'is_aktif' => true,
                    'created_at' => $now,
                    'updated_at' => $now,
                ],
                [
                    'stasiun_id' => $stasiunId['Stasiun Puteran'] ?? null,
                    'nama_parameter' => 'Babonan C Brix',
                    'operator_kondisi' => 'NONE',
                    'batas_bawah' => null,
                    'batas_atas' => null,
                    'is_aktif' => true,
                    'created_at' => $now,
                    'updated_at' => $now,
                ],
                [
                    'stasiun_id' => $stasiunId['Stasiun Puteran'] ?? null,
                    'nama_parameter' => 'Babonan C Pol',
                    'operator_kondisi' => 'NONE',
                    'batas_bawah' => null,
                    'batas_atas' => null,
                    'is_aktif' => true,
                    'created_at' => $now,
                    'updated_at' => $now,
                ],
                [
                    'stasiun_id' => $stasiunId['Stasiun Puteran'] ?? null,
                    'nama_parameter' => 'Babonan C HK',
                    'operator_kondisi' => '<',
                    'batas_bawah' => null,
                    'batas_atas' => 33,
                    'is_aktif' => true,
                    'created_at' => $now,
                    'updated_at' => $now,
                ],
                [
                    'stasiun_id' => $stasiunId['Stasiun Puteran'] ?? null,
                    'nama_parameter' => 'Babonan D Brix',
                    'operator_kondisi' => 'NONE',
                    'batas_bawah' => null,
                    'batas_atas' => null,
                    'is_aktif' => true,
                    'created_at' => $now,
                    'updated_at' => $now,
                ],
                [
                    'stasiun_id' => $stasiunId['Stasiun Puteran'] ?? null,
                    'nama_parameter' => 'Babonan D Pol',
                    'operator_kondisi' => 'NONE',
                    'batas_bawah' => null,
                    'batas_atas' => null,
                    'is_aktif' => true,
                    'created_at' => $now,
                    'updated_at' => $now,
                ],
                [
                    'stasiun_id' => $stasiunId['Stasiun Puteran'] ?? null,
                    'nama_parameter' => 'Babonan D HK',
                    'operator_kondisi' => '<',
                    'batas_bawah' => null,
                    'batas_atas' => 33,
                    'is_aktif' => true,
                    'created_at' => $now,
                    'updated_at' => $now,
                ],

                // STASIUN KETEL =======================================
                [
                    'stasiun_id' => $stasiunId['Stasiun Ketel'] ?? null,
                    'nama_parameter' => 'pH APK',
                    'operator_kondisi' => '>',
                    'batas_bawah' => 7,
                    'batas_atas' => null,
                    'is_aktif' => true,
                    'created_at' => $now,
                    'updated_at' => $now,
                ],
                [
                    'stasiun_id' => $stasiunId['Stasiun Ketel'] ?? null,
                    'nama_parameter' => 'Suhu APK',
                    'operator_kondisi' => 'NONE',
                    'batas_bawah' => null,
                    'batas_atas' => null,
                    'is_aktif' => true,
                    'created_at' => $now,
                    'updated_at' => $now,
                ],
                [
                    'stasiun_id' => $stasiunId['Stasiun Ketel'] ?? null,
                    'nama_parameter' => 'Kesadahan APK',
                    'operator_kondisi' => 'NONE',
                    'batas_bawah' => null,
                    'batas_atas' => null,
                    'is_aktif' => true,
                    'created_at' => $now,
                    'updated_at' => $now,
                ],
                [
                    'stasiun_id' => $stasiunId['Stasiun Ketel'] ?? null,
                    'nama_parameter' => 'pH EKM 1',
                    'operator_kondisi' => 'BETWEEN',
                    'batas_bawah' => 9.5,
                    'batas_atas' => 11.0,
                    'is_aktif' => true,
                    'created_at' => $now,
                    'updated_at' => $now,
                ],
                [
                    'stasiun_id' => $stasiunId['Stasiun Ketel'] ?? null,
                    'nama_parameter' => 'Turbidity EKM 1',
                    'operator_kondisi' => '<',
                    'batas_bawah' => null,
                    'batas_atas' => 100,
                    'is_aktif' => true,
                    'created_at' => $now,
                    'updated_at' => $now,
                ],
                [
                    'stasiun_id' => $stasiunId['Stasiun Ketel'] ?? null,
                    'nama_parameter' => 'Kesadahan EKM 1',
                    'operator_kondisi' => '<',
                    'batas_bawah' => null,
                    'batas_atas' => 100,
                    'is_aktif' => true,
                    'created_at' => $now,
                    'updated_at' => $now,
                ],
                [
                    'stasiun_id' => $stasiunId['Stasiun Ketel'] ?? null,
                    'nama_parameter' => 'TDS EKM 1',
                    'operator_kondisi' => '<',
                    'batas_bawah' => null,
                    'batas_atas' => 2500,
                    'is_aktif' => true,
                    'created_at' => $now,
                    'updated_at' => $now,
                ],
                [
                    'stasiun_id' => $stasiunId['Stasiun Ketel'] ?? null,
                    'nama_parameter' => 'pH EKM 2',
                    'operator_kondisi' => 'BETWEEN',
                    'batas_bawah' => 9.5,
                    'batas_atas' => 11.0,
                    'is_aktif' => true,
                    'created_at' => $now,
                    'updated_at' => $now,
                ],
                [
                    'stasiun_id' => $stasiunId['Stasiun Ketel'] ?? null,
                    'nama_parameter' => 'Turbidity EKM 2',
                    'operator_kondisi' => '<',
                    'batas_bawah' => null,
                    'batas_atas' => 100,
                    'is_aktif' => true,
                    'created_at' => $now,
                    'updated_at' => $now,
                ],
                [
                    'stasiun_id' => $stasiunId['Stasiun Ketel'] ?? null,
                    'nama_parameter' => 'Kesadahan EKM 2',
                    'operator_kondisi' => '<',
                    'batas_bawah' => null,
                    'batas_atas' => 100,
                    'is_aktif' => true,
                    'created_at' => $now,
                    'updated_at' => $now,
                ],
                [
                    'stasiun_id' => $stasiunId['Stasiun Ketel'] ?? null,
                    'nama_parameter' => 'TDS EKM 2',
                    'operator_kondisi' => '<',
                    'batas_bawah' => null,
                    'batas_atas' => 2500,
                    'is_aktif' => true,
                    'created_at' => $now,
                    'updated_at' => $now,
                ],
                [
                    'stasiun_id' => $stasiunId['Stasiun Ketel'] ?? null,
                    'nama_parameter' => 'pH EKM 3',
                    'operator_kondisi' => 'BETWEEN',
                    'batas_bawah' => 9.5,
                    'batas_atas' => 11.0,
                    'is_aktif' => true,
                    'created_at' => $now,
                    'updated_at' => $now,
                ],
                [
                    'stasiun_id' => $stasiunId['Stasiun Ketel'] ?? null,
                    'nama_parameter' => 'Turbidity EKM 3',
                    'operator_kondisi' => '<',
                    'batas_bawah' => null,
                    'batas_atas' => 100,
                    'is_aktif' => true,
                    'created_at' => $now,
                    'updated_at' => $now,
                ],
                [
                    'stasiun_id' => $stasiunId['Stasiun Ketel'] ?? null,
                    'nama_parameter' => 'Kesadahan EKM 3',
                    'operator_kondisi' => '<',
                    'batas_bawah' => null,
                    'batas_atas' => 100,
                    'is_aktif' => true,
                    'created_at' => $now,
                    'updated_at' => $now,
                ],
                [
                    'stasiun_id' => $stasiunId['Stasiun Ketel'] ?? null,
                    'nama_parameter' => 'TDS EKM 3',
                    'operator_kondisi' => '<',
                    'batas_bawah' => null,
                    'batas_atas' => 2500,
                    'is_aktif' => true,
                    'created_at' => $now,
                    'updated_at' => $now,
                ],
                [
                    'stasiun_id' => $stasiunId['Stasiun Ketel'] ?? null,
                    'nama_parameter' => 'pH EKM 4',
                    'operator_kondisi' => 'BETWEEN',
                    'batas_bawah' => 9.5,
                    'batas_atas' => 11.0,
                    'is_aktif' => true,
                    'created_at' => $now,
                    'updated_at' => $now,
                ],
                [
                    'stasiun_id' => $stasiunId['Stasiun Ketel'] ?? null,
                    'nama_parameter' => 'Turbidity EKM 4',
                    'operator_kondisi' => '<',
                    'batas_bawah' => null,
                    'batas_atas' => 100,
                    'is_aktif' => true,
                    'created_at' => $now,
                    'updated_at' => $now,
                ],
                [
                    'stasiun_id' => $stasiunId['Stasiun Ketel'] ?? null,
                    'nama_parameter' => 'Kesadahan EKM 4',
                    'operator_kondisi' => '<',
                    'batas_bawah' => null,
                    'batas_atas' => 100,
                    'is_aktif' => true,
                    'created_at' => $now,
                    'updated_at' => $now,
                ],
                [
                    'stasiun_id' => $stasiunId['Stasiun Ketel'] ?? null,
                    'nama_parameter' => 'TDS EKM 4',
                    'operator_kondisi' => '<',
                    'batas_bawah' => null,
                    'batas_atas' => 2500,
                    'is_aktif' => true,
                    'created_at' => $now,
                    'updated_at' => $now,
                ],
                [
                    'stasiun_id' => $stasiunId['Stasiun Ketel'] ?? null,
                    'nama_parameter' => 'pH EKM 5',
                    'operator_kondisi' => 'BETWEEN',
                    'batas_bawah' => 9.5,
                    'batas_atas' => 11.0,
                    'is_aktif' => true,
                    'created_at' => $now,
                    'updated_at' => $now,
                ],
                [
                    'stasiun_id' => $stasiunId['Stasiun Ketel'] ?? null,
                    'nama_parameter' => 'Turbidity EKM 5',
                    'operator_kondisi' => '<',
                    'batas_bawah' => null,
                    'batas_atas' => 100,
                    'is_aktif' => true,
                    'created_at' => $now,
                    'updated_at' => $now,
                ],
                [
                    'stasiun_id' => $stasiunId['Stasiun Ketel'] ?? null,
                    'nama_parameter' => 'Kesadahan EKM 5',
                    'operator_kondisi' => '<',
                    'batas_bawah' => null,
                    'batas_atas' => 100,
                    'is_aktif' => true,
                    'created_at' => $now,
                    'updated_at' => $now,
                ],
                [
                    'stasiun_id' => $stasiunId['Stasiun Ketel'] ?? null,
                    'nama_parameter' => 'TDS EKM 5',
                    'operator_kondisi' => '<',
                    'batas_bawah' => null,
                    'batas_atas' => 2500,
                    'is_aktif' => true,
                    'created_at' => $now,
                    'updated_at' => $now,
                ],
                [
                    'stasiun_id' => $stasiunId['Stasiun Ketel'] ?? null,
                    'nama_parameter' => 'pH KCC',
                    'operator_kondisi' => 'BETWEEN',
                    'batas_bawah' => 9.5,
                    'batas_atas' => 11.0,
                    'is_aktif' => true,
                    'created_at' => $now,
                    'updated_at' => $now,
                ],
                [
                    'stasiun_id' => $stasiunId['Stasiun Ketel'] ?? null,
                    'nama_parameter' => 'Turbidity KCC',
                    'operator_kondisi' => '<',
                    'batas_bawah' => null,
                    'batas_atas' => 100,
                    'is_aktif' => true,
                    'created_at' => $now,
                    'updated_at' => $now,
                ],
                [
                    'stasiun_id' => $stasiunId['Stasiun Ketel'] ?? null,
                    'nama_parameter' => 'Kesadahan KCC',
                    'operator_kondisi' => '<',
                    'batas_bawah' => null,
                    'batas_atas' => 100,
                    'is_aktif' => true,
                    'created_at' => $now,
                    'updated_at' => $now,
                ],
                [
                    'stasiun_id' => $stasiunId['Stasiun Ketel'] ?? null,
                    'nama_parameter' => 'TDS KCC',
                    'operator_kondisi' => '<',
                    'batas_bawah' => null,
                    'batas_atas' => 1500,
                    'is_aktif' => true,
                    'created_at' => $now,
                    'updated_at' => $now,
                ],
                [
                    'stasiun_id' => $stasiunId['Stasiun Ketel'] ?? null,
                    'nama_parameter' => 'Surplus APK Utara',
                    'operator_kondisi' => '<',
                    'batas_bawah' => null,
                    'batas_atas' => 500,
                    'is_aktif' => true,
                    'created_at' => $now,
                    'updated_at' => $now,
                ],
                [
                    'stasiun_id' => $stasiunId['Stasiun Ketel'] ?? null,
                    'nama_parameter' => 'Surplus APK Selatan',
                    'operator_kondisi' => '<',
                    'batas_bawah' => null,
                    'batas_atas' => 500,
                    'is_aktif' => true,
                    'created_at' => $now,
                    'updated_at' => $now,
                ],

                // STASIUN PRODUKSI =======================================
                [
                    'stasiun_id' => $stasiunId['Stasiun Produksi'] ?? null,
                    'nama_parameter' => 'Suhu Tetes',
                    'operator_kondisi' => '<',
                    'batas_bawah' => null,
                    'batas_atas' => 40,
                    'is_aktif' => true,
                    'created_at' => $now,
                    'updated_at' => $now,
                ],
                [
                    'stasiun_id' => $stasiunId['Stasiun Produksi'] ?? null,
                    'nama_parameter' => 'Kuintal Gula',
                    'operator_kondisi' => 'NONE',
                    'batas_bawah' => null,
                    'batas_atas' => null,
                    'is_aktif' => true,
                    'created_at' => $now,
                    'updated_at' => $now,
                ],
                [
                    'stasiun_id' => $stasiunId['Stasiun Produksi'] ?? null,
                    'nama_parameter' => 'Pol Gula',
                    'operator_kondisi' => 'NONE',
                    'batas_bawah' => null,
                    'batas_atas' => null,
                    'is_aktif' => true,
                    'created_at' => $now,
                    'updated_at' => $now,
                ],
                [
                    'stasiun_id' => $stasiunId['Stasiun Produksi'] ?? null,
                    'nama_parameter' => 'Kadar Air Gula',
                    'operator_kondisi' => '<',
                    'batas_bawah' => null,
                    'batas_atas' => 0.05,
                    'is_aktif' => true,
                    'created_at' => $now,
                    'updated_at' => $now,
                ],
                [
                    'stasiun_id' => $stasiunId['Stasiun Produksi'] ?? null,
                    'nama_parameter' => 'Icumsa Gula',
                    'operator_kondisi' => '<',
                    'batas_bawah' => null,
                    'batas_atas' => 300,
                    'is_aktif' => true,
                    'created_at' => $now,
                    'updated_at' => $now,
                ],
                [
                    'stasiun_id' => $stasiunId['Stasiun Produksi'] ?? null,
                    'nama_parameter' => 'Diameter Gula',
                    'operator_kondisi' => 'BETWEEN',
                    'batas_bawah' => 0.9,
                    'batas_atas' => 1.2,
                    'is_aktif' => true,
                    'created_at' => $now,
                    'updated_at' => $now,
                ],
                [
                    'stasiun_id' => $stasiunId['Stasiun Produksi'] ?? null,
                    'nama_parameter' => 'Suhu Gula',
                    'operator_kondisi' => '<',
                    'batas_bawah' => null,
                    'batas_atas' => 40,
                    'is_aktif' => true,
                    'created_at' => $now,
                    'updated_at' => $now,
                ],

                // NERACA WARNA =======================================
                [
                    'stasiun_id' => $stasiunId['Neraca Warna'] ?? null,
                    'nama_parameter' => 'NM Icumsa',
                    'operator_kondisi' => 'NONE',
                    'batas_bawah' => null,
                    'batas_atas' => null,
                    'is_aktif' => true,
                    'created_at' => $now,
                    'updated_at' => $now,
                ],
                [
                    'stasiun_id' => $stasiunId['Neraca Warna'] ?? null,
                    'nama_parameter' => 'NE Icumsa',
                    'operator_kondisi' => 'NONE',
                    'batas_bawah' => null,
                    'batas_atas' => null,
                    'is_aktif' => true,
                    'created_at' => $now,
                    'updated_at' => $now,
                ],
                [
                    'stasiun_id' => $stasiunId['Neraca Warna'] ?? null,
                    'nama_parameter' => 'NK Icumsa',
                    'operator_kondisi' => 'NONE',
                    'batas_bawah' => null,
                    'batas_atas' => null,
                    'is_aktif' => true,
                    'created_at' => $now,
                    'updated_at' => $now,
                ],
                [
                    'stasiun_id' => $stasiunId['Neraca Warna'] ?? null,
                    'nama_parameter' => 'NK Sulf. Icumsa',
                    'operator_kondisi' => 'NONE',
                    'batas_bawah' => null,
                    'batas_atas' => null,
                    'is_aktif' => true,
                    'created_at' => $now,
                    'updated_at' => $now,
                ],
                
            ];

            $parameter = array_merge($parameter, $this->buildAlcoholParameters($stasiunId->toArray(), $now));

            $parameter = array_map(function ($item) {
                $item['satuan'] = $item['satuan'] ?? $this->inferSatuan((string)($item['nama_parameter'] ?? ''));
                return $item;
            }, $parameter);

            $parameter = array_values(array_filter($parameter, fn ($item) => !empty($item['stasiun_id'])));

            if (!empty($parameter)) {
                foreach ($parameter as $item) {
                    DB::connection('pgsql')->table('mst_parameter')->updateOrInsert(
                        [
                            'stasiun_id' => $item['stasiun_id'],
                            'nama_parameter' => $item['nama_parameter'],
                        ],
                        [
                            'satuan' => $item['satuan'] ?? null,
                            'operator_kondisi' => $item['operator_kondisi'],
                            'batas_bawah' => $item['batas_bawah'],
                            'batas_atas' => $item['batas_atas'],
                            'is_aktif' => $item['is_aktif'],
                            'updated_at' => $item['updated_at'],
                            'created_at' => $item['created_at'],
                        ]
                    );
                }

                DB::connection('pgsql')->table('mst_parameter')
                    ->whereRaw('LOWER(nama_parameter) = ?', ['tekanan roll'])
                    ->update([
                        'is_aktif' => false,
                        'updated_at' => $now,
                    ]);
            }
        });
    }
}
